name: setup
class: center, middle, inverse

# Time to set up Git and GitHub

⤷ and get your project repository ready to go

---

.pull-left[
# Installing Git

### Windows and macOS

Download from <https://git-scm.com/>

Windows users may have to restart after installation to update the system PATH

### Linux

Install via package manager, e.g.

```sh
sudo apt install git
```
]

.pull-right[
# Installing a client

[Many options](https://git-scm.com/downloads/guis/), but to highlight a few:

♟ [**GitHub Desktop**](https://desktop.github.com/)

⤷ very simple client, only most basic features; integrates with GitHub

♜ [**GitKraken**](https://www.gitkraken.com/)

⤷ more features, fancy UI; free for _non-commercial_ use, requires account or GitHub sign-in

♛ **Your editor of choice**

⤷ many editors support version control from inside the editor<br>
.small[(e.g. Emacs with Magit, or Vim with Fugitive)]

♚ **The command line** `r emo::ji('smirk')`
]

---
name: github

# Collaborate with GitHub

`r emo::ji('exclamation')`
signing up with uni email ⟹ free private repos

--

## Getting started

1. Go to [**github.com**](https://github.com) and sign up with your `@student.aau.dk` email

2. Go to [**education.github.com/pack**](https://education.github.com/pack) and click _Get your Pack_

---
layout: true

## Setting up a repository (for the repo owner)

_NB: Only one person from each group needs to set up a project repository_

---

1. On GitHub, log in and click .gh-btn[`r octicon("repo")`New]

1. Fill in the details;

    - **Repository name:** P1
    - **Description:** P1 project for Group `<your group id>`
    - **🗹 Private** (can be set later, if you don't have the student discount yet)
    - **🗹 Initialize this repository with a README**
    - **Add .gitignore:** TeX

1. Go to .gh-menu[`r octicon("gear")`Settings] 🠪 .gh-menu[Collaborators]

1. Add each of your group members as a collaborator

1. Go to .gh-menu[`r octicon("code")`Code] and click .gh-btn[Clone or download`r octicon("chevron-down")`]

1. Click .gh-menu[Open in Desktop] to get started (or copy the URL and open it with your Git client, if you don't use GitHub Desktop)

---

1. Download a template from [**janusvm.github.io/aau-project-template**](https://janusvm.github.io/aau-project-template/)

1. Unpack it in the folder where you cloned the project

1. In GitHub Desktop (or whatever client you use), stage all the new files

1. Commit with a message like "Add project template files"

1. Push to GitHub

---
layout: false

## Setting up a repository (for the collaborators)

1. Go to the repository page on GitHub (github.com/owner/repo)

1. Click .gh-btn[Clone or download `r octicon("chevron-down")`]

1. Clone the repository (by clicking .gh-menu[Open in Desktop] with GH Desktop, or by using the URL with another client)

After this, you're ready to start writing!


---

## Remember the workflow

1. **Pull** from GitHub to get the latest changes from the other group members

1. Work on the project

1. **Add** and **Commit** related changes together

1. **Pull** again, in case new commits have been pushed in the meantime

1. If there are any conflicts, resolve them and commit the merge

1. **Push** your changes to GitHub, so the other group members can get them
